### ISSUE TITLE
Question: How to retrieve only one item from the store instead of a whole page?

### ISSUE THREAD

**Issue by stefanpartheym** [cyon/vuex-pagination#17]
Hey folks,

is there a way to retrieve only one item from the store? Given an index or a certain key or ID to identify the item by?

I have the following scenario:
I have an overview component, that displays a paginated list of items (route: `.../items`).
And I have a detail component, that displays certain details for a given item (route: `.../items/unique-item-id`).
Now the thing is, I want the detail component to parse the item ID from the URL (`unique-item-id` in this case). And in the detail component however, I must retrieve the item data from the store using the given ID.
I want to avoid to pass the whole item object to the detail component, to be able to have certain URL's like `http://localhost:8080/items/unique-item-id` working.

Best regards
Stefan

**Comment by MaxGfeller** [comment]
Hi @stefanpartheym 👋

Usually, at least with REST APIs, you'd get additional details when fetching a single resource rather than a list. In this case you'd do the fetching outside of vuex-pagination, e.g. just in your component.

However, if the displayed data is the same as in the paginated resource (no additional details), then you could do something like this:

```javascript
import { resource } from 'vuex-pagination'

resource(resourceName).fetchRange({
  pageFrom: from,
  pageTo: to
})
```

But in this case you'd have to know which page this item was in.

**Comment by stefanpartheym** [comment]
Ok I see, thanks.
So, it would make sense to redesign my stores structure to just use `vuex-pagination` for fetching pages of items (exactly what it's meant to be, kinda obvious). And as soon as I want to fetch details about one specific item use a separate store(-module).  It would actually create a small amount of redundancy - due to the fact that I then would have item specific values twice in my store - which however, is acceptable I think. Of course I'd need to update both stores whenever I update the item, but I think this is the cleanest solution after all.
